### PR TITLE
Fix service ports

### PR DESCRIPTION
**Pull request by tetsun**
## TL;DR

Change spec.ports[*].port of service.yaml.

## Description

When an aws-alb-ingress-controller creates an alb,
the target group of the alb cannot create listeners and targetgroups.
And the aws-alb-ingress-controller outputs the following message.

```
E0716 06:15:53.138070       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to find 8090 port on service confluence-server"  "controller"="alb-ingress-controller" "request"={"Namespace":"confluence","Name":"confluence-server"}
```

So I changed service port and `ATL_TOMCAT_PORT` to 80, but then tomcat failed to launch.

I think the service port should be set via values.

### CODE REVIEW

**Comment by javimox** [comment]
Hi @tetsun ,

Thanks for your PR and your feedback. If I merge the PR it will break the Charts for other scenarios, as `port` and `targetPort` will be then the same. 

We can use values instead of hardcoding the port, though. That would be easy, but first I would like to ask you what do you have in your case in `service.port` of `values` and what do you have then in `service.yaml`  ?


Regards,

**Comment by tetsun** [comment]
@javimox 

Thanks for your reply.
My cases are as follows.

### case1
- values
  - `service.port = 8090`
- results
  - the listen port of svc is `80` https://github.com/javimox/helm-charts/blob/0dfdf031bf7dbd5db137ee6971f746c817c301ee/charts/confluence-server/templates/service.yaml#L14
  - the target port of ingress is `8090` https://github.com/javimox/helm-charts/blob/0dfdf031bf7dbd5db137ee6971f746c817c301ee/charts/confluence-server/templates/ingress.yaml#L38
  - then the ingress-controller cannot find the svc (port mismatching)

### case2
- values
  - `service.port = 80`
  - `envVars.ATL_TOMCAT_PORT = 80`
- results
  - the listen port of svc is `80` https://github.com/javimox/helm-charts/blob/0dfdf031bf7dbd5db137ee6971f746c817c301ee/charts/confluence-server/templates/service.yaml#L14
  - the target port of ingress is `80` https://github.com/javimox/helm-charts/blob/0dfdf031bf7dbd5db137ee6971f746c817c301ee/charts/confluence-server/templates/ingress.yaml#L38
  - then the ingress-controller can find the svc (port matching!!)
  - but the tomcat `failed to launch`


So I think

- we should be able to use values to select the port of svc
or
- the target port of ingress should be `80` (`443` in case https)

**Comment by javimox** [comment]
Hi @tetsun,

could you please take a look to the commits I added to your PR and test the Chart? It'd be great to get some more feedback. Ty.

**Comment by tetsun** [comment]
Hi @javimox 

I tried but the pods failed to launch with the following logs.

```
INFO:root:Generating /opt/atlassian/confluence/conf/server.xml from template server.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/seraph-config.xml from template seraph-config.xml.j2
INFO:root:Generating /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties from template confluence-init.properties.j2
INFO:root:Generating /var/atlassian/application-data/confluence/confluence.cfg.xml from template confluence.cfg.xml.j2
Traceback (most recent call last):
  File "/entrypoint.py", line 17, in <module>
    user=RUN_USER, group=RUN_GROUP, overwrite=False)
  File "/entrypoint_helpers.py", line 57, in gen_cfg
    cfg = jenv.get_template(tmpl).render(env)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/opt/atlassian/etc/confluence.cfg.xml.j2", line 26, in top-level template code
    <property name="hibernate.connection.driver_class">{{ databases[atl_db_type][0] }}</property>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'portgresql'
```

`portgresql`... typo? 🤔 
I wonder it's a bug of the confluence image.
I will try again next Monday.

Thanks

**Comment by javimox** [comment]
Uhmm... I just installed the last version without issues. What's the content of your `databaseConnection.type`?

**Comment by tetsun** [comment]
@javimox 

Sorry, my setting was wrong about databaseConnection :sob:

And then, `ATL_PROXY_NAME` in the configmap.yaml has an issue.
`{{ index .Values.ingress.hosts 0 | quote }}` returns `map`.
( eg. helm diff shows `+   ATL_PROXY_NAME: "map[host:confluence.my-domain paths:[/]]"`)

So I modified it to `{{ (index .Values.ingress.hosts 0).host | quote }}` and cf succeeded to launch.
Plz review it.

Thanks

**Comment by javimox** [comment]
> @javimox
> 
> Sorry, my setting was wrong about databaseConnection 😭
> 
> And then, `ATL_PROXY_NAME` in the configmap.yaml has an issue.
> `{{ index .Values.ingress.hosts 0 | quote }}` returns `map`.
> ( eg. helm diff shows `+ ATL_PROXY_NAME: "map[host:confluence.my-domain paths:[/]]"`)
> 
> So I modified it to `{{ (index .Values.ingress.hosts 0).host | quote }}` and cf succeeded to launch.
> Plz review it.
> 
> Thanks

LGTM @tetsun , many thanks!

**Pull request merged**
